const initialAsesores = [
  {
    id: 1,
    nombre: 'SASKYA',
    email: 'saskya@albru.com',
    telefono: '+51 987654321',
    estado: 'Activo',
    clientesAsignados: 0,
    clientesAtendidos: 0,
    ventasHoy: 0,
    ventasMes: 52,
    metaMensual: 55,
    eficiencia: 0,
    ultimaActividad: 'Inicio del día',
    sala: 'Sala 1'
  },
  {
    id: 2,
    nombre: 'KAREN',
    email: 'karen@albru.com',
    telefono: '+51 987654322',
    estado: 'Activo',
    clientesAsignados: 0,
    clientesAtendidos: 0,
    ventasHoy: 0,
    ventasMes: 48,
    metaMensual: 50,
    eficiencia: 0,
    ultimaActividad: 'Inicio del día',
    sala: 'Sala 1'
  },
  {
    id: 3,
    nombre: 'CESAR',
    email: 'cesar@albru.com',
    telefono: '+51 987654323',
    estado: 'Activo',
    clientesAsignados: 0,
    clientesAtendidos: 0,
    ventasHoy: 0,
    ventasMes: 41,
    metaMensual: 45,
    eficiencia: 0,
    ultimaActividad: 'Inicio del día',
    sala: 'Sala 1'
  },
  {
    id: 4,
    nombre: 'ALBERTO',
    email: 'alberto@albru.com',
    telefono: '+51 987654324',
    estado: 'Activo',
    clientesAsignados: 0,
    clientesAtendidos: 0,
    ventasHoy: 0,
    ventasMes: 35,
    metaMensual: 40,
    eficiencia: 0,
    ultimaActividad: 'Inicio del día',
    sala: 'Sala 1'
  },
  {
    id: 5,
    nombre: 'SEBASTIAN',
    email: 'sebastian@albru.com',
    telefono: '+51 987654325',
    estado: 'Activo',
    clientesAsignados: 0,
    clientesAtendidos: 0,
    ventasHoy: 0,
    ventasMes: 38,
    metaMensual: 42,
    eficiencia: 0,
    ultimaActividad: 'Inicio del día',
    sala: 'Sala 2'
  },
  {
    id: 6,
    nombre: 'JUAN',
    email: 'juan@albru.com',
    telefono: '+51 987654326',
    estado: 'Activo',
    clientesAsignados: 0,
    clientesAtendidos: 0,
    ventasHoy: 0,
    ventasMes: 33,
    metaMensual: 38,
    eficiencia: 0,
    ultimaActividad: 'Inicio del día',
    sala: 'Sala 2'
  },
  {
    id: 7,
    nombre: 'JHUDIT',
    email: 'jhudit@albru.com',
    telefono: '+51 987654327',
    estado: 'Activo',
    clientesAsignados: 0,
    clientesAtendidos: 0,
    ventasHoy: 0,
    ventasMes: 29,
    metaMensual: 35,
    eficiencia: 0,
    ultimaActividad: 'Inicio del día',
    sala: 'Sala 2'
  },
  {
    id: 8,
    nombre: 'GINGER',
    email: 'ginger@albru.com',
    telefono: '+51 987654328',
    estado: 'Activo',
    clientesAsignados: 0,
    clientesAtendidos: 0,
    ventasHoy: 0,
    ventasMes: 36,
    metaMensual: 40,
    eficiencia: 0,
    ultimaActividad: 'Inicio del día',
    sala: 'Sala 2'
  },
  {
    id: 9,
    nombre: 'ANDREA',
    email: 'andrea@albru.com',
    telefono: '+51 987654329',
    estado: 'Activo',
    clientesAsignados: 0,
    clientesAtendidos: 0,
    ventasHoy: 0,
    ventasMes: 31,
    metaMensual: 36,
    eficiencia: 0,
    ultimaActividad: 'Inicio del día',
    sala: 'Sala 3'
  },
  {
    id: 10,
    nombre: 'GABRIEL',
    email: 'gabriel@albru.com',
    telefono: '+51 987654330',
    estado: 'Activo',
    clientesAsignados: 0,
    clientesAtendidos: 0,
    ventasHoy: 0,
    ventasMes: 44,
    metaMensual: 48,
    eficiencia: 0,
    ultimaActividad: 'Inicio del día',
    sala: 'Sala 3'
  },
  {
    id: 11,
    nombre: 'DANITXA',
    email: 'danitxa@albru.com',
    telefono: '+51 987654331',
    estado: 'Activo',
    clientesAsignados: 0,
    clientesAtendidos: 0,
    ventasHoy: 0,
    ventasMes: 26,
    metaMensual: 32,
    eficiencia: 0,
    ultimaActividad: 'Inicio del día',
    sala: 'Sala 3'
  },
  {
    id: 12,
    nombre: 'MIA',
    email: 'mia@albru.com',
    telefono: '+51 987654332',
    estado: 'Activo',
    clientesAsignados: 0,
    clientesAtendidos: 0,
    ventasHoy: 0,
    ventasMes: 28,
    metaMensual: 33,
    eficiencia: 0,
    ultimaActividad: 'Inicio del día',
    sala: 'Sala 3'
  }
];

export default initialAsesores;