const initialAsesores = [
  {
    id: 1,
    nombre: 'Juan Carlos Mendez',
    email: 'juan.mendez@albru.com',
    telefono: '+51 987654321',
    estado: 'Activo',
    clientesAsignados: 25,
    clientesAtendidos: 18,
    ventasHoy: 3,
    ventasMes: 45,
    metaMensual: 50,
    eficiencia: 92,
    ultimaActividad: 'Hace 5 min',
    sala: 'Sala 1'
  },
  {
    id: 2,
    nombre: 'María Elena Saskya',
    email: 'maria.saskya@albru.com',
    telefono: '+51 987654322',
    estado: 'Activo',
    clientesAsignados: 30,
    clientesAtendidos: 28,
    ventasHoy: 5,
    ventasMes: 52,
    metaMensual: 50,
    eficiencia: 95,
    ultimaActividad: 'Hace 2 min',
    sala: 'Sala 2'
  },
  {
    id: 3,
    nombre: 'Mia Rodriguez',
    email: 'mia.rodriguez@albru.com',
    telefono: '+51 987654323',
    estado: 'Ocupado',
    clientesAsignados: 22,
    clientesAtendidos: 20,
    ventasHoy: 2,
    ventasMes: 38,
    metaMensual: 40,
    eficiencia: 88,
    ultimaActividad: 'En llamada',
    sala: 'Sala 2'
  },
  {
    id: 4,
    nombre: 'Carlos Alberto Vega',
    email: 'carlos.vega@albru.com',
    telefono: '+51 987654324',
    estado: 'Activo',
    clientesAsignados: 28,
    clientesAtendidos: 24,
    ventasHoy: 4,
    ventasMes: 41,
    metaMensual: 45,
    eficiencia: 85,
    ultimaActividad: 'Hace 10 min',
    sala: 'Sala 2'
  },
  {
    id: 5,
    nombre: 'Ana Lucía Torres',
    email: 'ana.torres@albru.com',
    telefono: '+51 987654325',
    estado: 'Activo',
    clientesAsignados: 26,
    clientesAtendidos: 23,
    ventasHoy: 3,
    ventasMes: 43,
    metaMensual: 45,
    eficiencia: 90,
    ultimaActividad: 'Hace 3 min',
    sala: 'Sala 2'
  },
  {
    id: 6,
    nombre: 'Roberto Silva Lima',
    email: 'roberto.silva@albru.com',
    telefono: '+51 987654326',
    estado: 'Descanso',
    clientesAsignados: 20,
    clientesAtendidos: 16,
    ventasHoy: 1,
    ventasMes: 32,
    metaMensual: 40,
    eficiencia: 78,
    ultimaActividad: 'Hace 30 min',
    sala: 'Sala 2'
  },
  {
    id: 7,
    nombre: 'Patricia Morales',
    email: 'patricia.morales@albru.com',
    telefono: '+51 987654327',
    estado: 'Activo',
    clientesAsignados: 24,
    clientesAtendidos: 22,
    ventasHoy: 2,
    ventasMes: 39,
    metaMensual: 42,
    eficiencia: 87,
    ultimaActividad: 'Hace 7 min',
    sala: 'Sala 2'
  },
  {
    id: 8,
    nombre: 'Diego Fernando Cruz',
    email: 'diego.cruz@albru.com',
    telefono: '+51 987654328',
    estado: 'Ocupado',
    clientesAsignados: 27,
    clientesAtendidos: 25,
    ventasHoy: 4,
    ventasMes: 47,
    metaMensual: 50,
    eficiencia: 91,
    ultimaActividad: 'En llamada',
    sala: 'Sala 2'
  },
  {
    id: 9,
    nombre: 'Sofía Ramírez',
    email: 'sofia.ramirez@albru.com',
    telefono: '+51 987654329',
    estado: 'Activo',
    clientesAsignados: 23,
    clientesAtendidos: 21,
    ventasHoy: 3,
    ventasMes: 36,
    metaMensual: 40,
    eficiencia: 83,
    ultimaActividad: 'Hace 15 min',
    sala: 'Sala 2'
  },
  {
    id: 10,
    nombre: 'Luis Miguel Herrera',
    email: 'luis.herrera@albru.com',
    telefono: '+51 987654330',
    estado: 'Activo',
    clientesAsignados: 29,
    clientesAtendidos: 26,
    ventasHoy: 5,
    ventasMes: 49,
    metaMensual: 50,
    eficiencia: 94,
    ultimaActividad: 'Hace 1 min',
    sala: 'Sala 1'
  },
  {
    id: 11,
    nombre: 'Carmen Rosa López',
    email: 'carmen.lopez@albru.com',
    telefono: '+51 987654331',
    estado: 'Offline',
    clientesAsignados: 18,
    clientesAtendidos: 14,
    ventasHoy: 0,
    ventasMes: 28,
    metaMensual: 35,
    eficiencia: 75,
    ultimaActividad: 'Hace 2 horas',
    sala: 'Sala 2'
  },
  {
    id: 12,
    nombre: 'Fernando Castillo',
    email: 'fernando.castillo@albru.com',
    telefono: '+51 987654332',
    estado: 'Activo',
    clientesAsignados: 25,
    clientesAtendidos: 22,
    ventasHoy: 3,
    ventasMes: 42,
    metaMensual: 45,
    eficiencia: 86,
    ultimaActividad: 'Hace 8 min',
    sala: 'Sala 2'
  },
  {
    id: 13,
    nombre: 'Valeria Gutierrez',
    email: 'valeria.gutierrez@albru.com',
    telefono: '+51 987654333',
    estado: 'Ocupado',
    clientesAsignados: 21,
    clientesAtendidos: 19,
    ventasHoy: 2,
    ventasMes: 34,
    metaMensual: 38,
    eficiencia: 81,
    ultimaActividad: 'En llamada',
    sala: 'Sala 2'
  },
  {
    id: 14,
    nombre: 'Ricardo Fernández',
    email: 'ricardo.fernandez@albru.com',
    telefono: '+51 987654334',
    estado: 'Activo',
    clientesAsignados: 26,
    clientesAtendidos: 24,
    ventasHoy: 4,
    ventasMes: 44,
    metaMensual: 48,
    eficiencia: 89,
    ultimaActividad: 'Hace 4 min',
    sala: 'Sala 2'
  }
];

export default initialAsesores;