SET NAMES utf8mb4;
LOAD DATA INFILE '/tmp/clientes_updated.csv' 
INTO TABLE clientes_temp 
CHARACTER SET utf8mb4 
FIELDS TERMINATED BY ';' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n' 
IGNORE 1 LINES;
